name: Release Docker Images

on:
  push:
    tags:
      - v*

jobs:
  build-image:
    strategy:
      matrix:
        java-version: [8-jre, 11-jre, 17-jre]
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: seepine
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Get Meta
        run: |
          echo REPO_VERSION=$(echo ${{ github.ref }} | awk -F"/" '{print $3}' | awk -F"v" '{print $2}') >> $GITHUB_ENV

      - name: Build and push base
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
            linux/arm/v6
            linux/arm/v7
            linux/ppc64le
            linux/s390x
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/alpine:latest
            ${{ env.DOCKER_USERNAME }}/alpine:${{ env.REPO_VERSION }}

      - name: Build and push wait
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.wait
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
            linux/arm/v6
            linux/arm/v7
            linux/ppc64le
            linux/s390x
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/alpine:wait
            ${{ env.DOCKER_USERNAME }}/alpine:wait-${{ env.REPO_VERSION }}

      - name: Build and push glibc
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.glibc
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
            linux/arm/v6
            linux/arm/v7
            linux/ppc64le
            linux/s390x
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/alpine:glibc
            ${{ env.DOCKER_USERNAME }}/alpine:glibc-${{ env.REPO_VERSION }}

      - name: Build and push node
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.node
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
            linux/arm/v6
            linux/arm/v7
            linux/ppc64le
            linux/s390x
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/alpine:node
            ${{ env.DOCKER_USERNAME }}/alpine:node-${{ env.REPO_VERSION }}

      - name: Build and push node
        uses: docker/build-push-action@v4
        env:
          JAVA_VERSION: ${{ matrix.java-version }}
        with:
          context: .
          file: Dockerfile.jre
          build-args: JAVA_VERSION=${{ env.JAVA_VERSION }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/alpine:${{ env.JAVA_VERSION }}
